export const SIGNIN_WORKER_ACTION = {
  GET_WORKERDATA: "GET_WORKERDATA",
  POST_WORKERDATA: "POST_WORKERDATA",
  DELETE_WORKERDATA: "DELETE_WORKERDATA",
};

export const SIGNIN_EMPLOYER_ACTION = {
  GET_EMPLOYERDATA: "GET_EMPLOYERDATA",
  POST_EMPLOYERDATA: "POST_EMPLOYERDATA",
  DELETE_EMPLOYERDATA: "DELETE_EMPLOYERDATA",
}; 

